// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl2OBpI7KRG5rcO9q8NRRwzWpd8K0Bm2E',
    appId: '1:509208658163:web:5621974532bb5302847786',
    messagingSenderId: '509208658163',
    projectId: 'besty-1790e',
    authDomain: 'besty-1790e.firebaseapp.com',
    storageBucket: 'besty-1790e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUlap0oUjbzXSkxS3NHW1ndBlgbzYgd-8',
    appId: '1:509208658163:android:8729ffcec6b07f60847786',
    messagingSenderId: '509208658163',
    projectId: 'besty-1790e',
    storageBucket: 'besty-1790e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzs8u1JfMmbIZ4y13GNJajS8HbaEp5b2w',
    appId: '1:509208658163:ios:0a5e1bf5a01364a6847786',
    messagingSenderId: '509208658163',
    projectId: 'besty-1790e',
    storageBucket: 'besty-1790e.appspot.com',
    iosBundleId: 'com.example.besty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzs8u1JfMmbIZ4y13GNJajS8HbaEp5b2w',
    appId: '1:509208658163:ios:0275ce0383ad758d847786',
    messagingSenderId: '509208658163',
    projectId: 'besty-1790e',
    storageBucket: 'besty-1790e.appspot.com',
    iosBundleId: 'com.example.besty.RunnerTests',
  );
}
